"""
Pydantic models for agent outputs and structured data.

This module defines typed models for:
- Agent-specific outputs (Investigation, Analysis, Response, Reports)
- Tool inputs and outputs
- Structured findings and recommendations
- MITRE ATT&CK mappings

All models use Pydantic for validation and serialization.
"""
from pydantic import BaseModel, Field, validator
from typing import List, Optional, Dict, Any, Literal
from datetime import datetime
from enum import Enum


# ==================== ENUMS ====================

class FindingType(str, Enum):
    """Type of security finding."""
    SUSPICIOUS_ACTIVITY = "suspicious_activity"
    IOC = "ioc"
    NORMAL = "normal"
    ANOMALY = "anomaly"


class SeverityLevel(str, Enum):
    """Severity levels for findings and threats."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AttackStatus(str, Enum):
    """Status of an attack."""
    ACTIVE = "active"
    CONTAINED = "contained"
    PAST = "past"
    UNKNOWN = "unknown"


class ResponseStrategy(str, Enum):
    """Response strategy type."""
    CONTAINMENT = "containment"
    ERADICATION = "eradication"
    RECOVERY = "recovery"


class ActionType(str, Enum):
    """Types of response actions."""
    BLOCK_IP = "block_ip"
    BLOCK_DOMAIN = "block_domain"
    ISOLATE_HOST = "isolate_host"
    DISABLE_USER = "disable_user"
    KILL_PROCESS = "kill_process"
    DELETE_FILE = "delete_file"
    UPDATE_RULE = "update_rule"
    CREATE_CASE = "create_case"
    ADD_OBSERVABLE = "add_observable"
    RUN_ANALYZER = "run_analyzer"


# ==================== COMMON STRUCTURES ====================

class Finding(BaseModel):
    """A security finding from investigation."""
    type: FindingType
    description: str
    severity: SeverityLevel
    evidence: str
    mitre_technique: Optional[str] = None
    timestamp: Optional[datetime] = None
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    
    @validator('mitre_technique')
    def validate_mitre_technique(cls, v):
        """Validate MITRE technique format (T1234 or T1234.001)."""
        if v and not v.startswith('T'):
            raise ValueError('MITRE technique must start with T')
        return v


class IOC(BaseModel):
    """Indicator of Compromise."""
    type: Literal["ip", "domain", "hash", "url", "email", "file"]
    value: str
    source: str = "investigation"
    first_seen: Optional[datetime] = None
    last_seen: Optional[datetime] = None
    tags: List[str] = Field(default_factory=list)
    tlp: Literal["white", "green", "amber", "red"] = "amber"


class MITREMapping(BaseModel):
    """MITRE ATT&CK mapping."""
    tactic: str  # TA0001
    technique: str  # T1234
    sub_technique: Optional[str] = None  # T1234.001
    evidence: str
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)


class TimelineEvent(BaseModel):
    """Event in a timeline."""
    timestamp: datetime
    event: str
    source: str
    actor: Optional[str] = None
    significance: Optional[str] = None


class Recommendation(BaseModel):
    """Security recommendation."""
    priority: SeverityLevel
    action: str
    justification: str
    estimated_effort: Optional[str] = None  # "5 minutes", "1 hour", etc.
    requires_approval: bool = False


# ==================== INVESTIGATOR MODELS ====================

class InvestigationQuery(BaseModel):
    """A query to execute during investigation."""
    tool: str  # wazuh, thehive, misp, cortex
    action: str  # search_alerts, get_agent, etc.
    parameters: Dict[str, Any] = Field(default_factory=dict)
    purpose: str


class InvestigationPlan(BaseModel):
    """Plan generated by Investigator."""
    investigation_plan: str
    queries: List[InvestigationQuery]
    expected_findings: str


class InvestigationResult(BaseModel):
    """Result from Investigator agent."""
    status: Literal["completed", "partial", "failed"]
    findings: List[Finding]
    timeline: List[TimelineEvent]
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    iocs: List[IOC] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    queries_executed: int = 0
    queries_successful: int = 0


# ==================== ANALYST MODELS ====================

class AttackHypothesis(BaseModel):
    """Hypothesis about an attack."""
    name: str
    confidence: float = Field(ge=0.0, le=1.0)
    description: str
    supporting_evidence: List[str] = Field(default_factory=list)


class ThreatActorAssessment(BaseModel):
    """Assessment of threat actor."""
    sophistication: Literal["apt", "organized", "script_kiddie", "unknown"]
    motivation: Literal["financial", "espionage", "hacktivism", "unknown"]
    indicators: List[str] = Field(default_factory=list)


class CompromiseScope(BaseModel):
    """Scope of compromise."""
    confirmed: List[str] = Field(default_factory=list)
    suspected: List[str] = Field(default_factory=list)
    at_risk: List[str] = Field(default_factory=list)


class CorrelationResult(BaseModel):
    """Result from event correlation."""
    correlation_summary: str
    attack_hypothesis: AttackHypothesis
    mitre_mapping: List[MITREMapping]
    kill_chain_phase: str
    severity_assessment: Dict[str, Any]
    related_iocs: List[IOC] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)


class ThreatAssessment(BaseModel):
    """Threat assessment from Analyst."""
    threat_level: SeverityLevel
    attack_status: AttackStatus
    compromise_scope: CompromiseScope
    threat_actor_assessment: ThreatActorAssessment
    immediate_risks: List[str] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)


class AnalysisResult(BaseModel):
    """Complete analysis result from Analyst agent."""
    status: Literal["completed", "partial", "failed"]
    correlation: Optional[CorrelationResult] = None
    threat_assessment: Optional[ThreatAssessment] = None
    executive_summary: str = ""
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)


# ==================== RESPONDER MODELS ====================

class ResponseAction(BaseModel):
    """An action to take in response to a threat."""
    id: Optional[str] = None
    type: ActionType
    target: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    justification: str
    risk_level: SeverityLevel
    rollback_procedure: str
    requires_approval: bool = True
    system_risk_level: Optional[str] = None


class ResponsePlan(BaseModel):
    """Response plan from Responder."""
    response_strategy: ResponseStrategy
    urgency: Literal["immediate", "urgent", "planned"]
    actions: List[ResponseAction]
    prerequisites: List[str] = Field(default_factory=list)
    success_criteria: List[str] = Field(default_factory=list)
    communication_plan: str


class ActionResult(BaseModel):
    """Result of executing a response action."""
    action: ResponseAction
    status: Literal["success", "failed", "dry_run", "pending"]
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class ResponseReport(BaseModel):
    """Report from Responder agent."""
    status: Literal["completed", "partial", "pending"]
    summary: Dict[str, Any]
    executed_actions: List[ActionResult]
    pending_actions: List[ResponseAction] = Field(default_factory=list)
    rollback_info: List[Dict[str, str]] = Field(default_factory=list)
    next_steps: List[str] = Field(default_factory=list)
    communication: str = ""


# ==================== REPORTER MODELS ====================

class ReportMetadata(BaseModel):
    """Metadata for a report."""
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    generator: str = "reporter"
    incident_id: Optional[str] = None
    alert_id: Optional[str] = None
    data_sources: int = 0
    tasks_analyzed: int = 0


class IncidentReport(BaseModel):
    """Incident report from Reporter."""
    type: Literal["incident_report", "executive_summary", "timeline", "technical_report"]
    format: Literal["markdown", "html", "json"]
    content: str
    metadata: ReportMetadata
    attachments: List[Dict[str, str]] = Field(default_factory=list)
    raw_data: Optional[Dict[str, Any]] = None


class Timeline(BaseModel):
    """Timeline report."""
    type: Literal["timeline"]
    format: Literal["json", "markdown"]
    timeline: List[TimelineEvent]
    key_moments: List[str] = Field(default_factory=list)
    duration: Optional[str] = None
    metadata: ReportMetadata


# ==================== TOOL MODELS ====================

class ToolInput(BaseModel):
    """Base model for tool inputs."""
    tool_name: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    timeout: int = 60


class ToolOutput(BaseModel):
    """Base model for tool outputs."""
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    execution_time: float = 0.0


# ==================== VALIDATION HELPERS ====================

def validate_investigation_result(data: dict) -> InvestigationResult:
    """Validate and parse investigation result."""
    return InvestigationResult(**data)


def validate_analysis_result(data: dict) -> AnalysisResult:
    """Validate and parse analysis result."""
    return AnalysisResult(**data)


def validate_response_plan(data: dict) -> ResponsePlan:
    """Validate and parse response plan."""
    return ResponsePlan(**data)


def validate_incident_report(data: dict) -> IncidentReport:
    """Validate and parse incident report."""
    return IncidentReport(**data)
